# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
        class: AppBundle\Admin\RecordAdmin
        arguments: [~, AppBundle\Entity\Record, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Host managment",label: Records }

    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User managment",label: Users }